name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      timeout-minutes: 10
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
        pip install -e .

    - name: Build documentation
      timeout-minutes: 10
      run: |
        cd docs
        # Ensure _static directory exists
        mkdir -p _static
        # Show Python and Sphinx versions for debugging
        python -c "import sys; print(f'Python: {sys.version}')"
        python -c "import sphinx; print(f'Sphinx: {sphinx.__version__}')"
        python -c "import myst_parser; print(f'MyST Parser: {myst_parser.__version__}')" || echo "MyST Parser not available"
        # Build documentation with verbose output
        sphinx-build -b html -v . _build/html
        touch _build/html/.nojekyll

    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/_build/html/

  deploy-docs:
    if: github.ref == 'refs/heads/main'
    needs: build-docs
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Download documentation
      uses: actions/download-artifact@v4
      with:
        name: documentation
        path: docs/

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
